name: Auto Cache Busting for Changed Files

on:
  push:
    branches:
      - main  # اجرا روی شاخه اصلی

jobs:
  cache-busting:
    runs-on: ubuntu-latest

    steps:
      # مرحله 1: کلون کردن ریپازیتوری
      - name: Checkout Repository
        uses: actions/checkout@v3
      # مرحله 4: نمایش تغییرات
      - name: Show Changes
        run: git diff
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          debug: true
          script: |
           cd /var/www/digitall.ui
           git pull origin main
           sudo systemctl reload nginx

